development:
  clients:
    default:
      uri: mongodb+srv://<username>:<password>@cluster0.rbsusvt.mongodb.net/inspiration?retryWrites=true&w=majority
      options:
        server_selection_timeout: 5